[package]
name = "fibonacci-sequence"
version = "1.1.0"
authors = ["Cesar D. Velandia <cesar@velandia.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
